config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'

  resources :case_studies, only: [:index, :show ]
  resources :skills, only: [:index, :show ]

  namespace :admin do
    get '/' => 'dashboard#index', as: 'dashboard_index'

    resources :case_studies
    resources :case_study_gallery_images, only: [:edit, :update]

    resources :fit_bit_stats, only: [:index]

    resources :skills

    resources :curriculum_vitaes
  end
end

app/models/skill.rb
# @author Matthew Rayner
# @since 0.1
class Skill < ActiveRecord::Base
  validates :title,
            :level,
            presence: {
              message: I18n.t('.skill.title_validation')
            }
  validates :svg_logo,
            :image_logo,
            presence: {
              message: I18n.t('.skill.logo_validation')
            }

  mount_uploader :svg_logo, SvgUploader
  mount_uploader :image_logo, LogoUploader

  validates_numericality_of :level,
                            greater_than_or_equal_to: 0.0,
                            less_than_or_equal_to: 100.0

  has_and_belongs_to_many :case_studies
end

app/controllers/admin/skills_controller.rb
module Admin
  # Allow a user to view, create and edit skills from within the admin
  # interface.
  #
  # @author Matthew Rayner
  # @since 0.1
  class SkillsController < Admin::BaseController
    def index
      @skills = Skill.all
    end

    def show
      @skill = Skill.find_by(id: params[:id])
      not_found if @skill.nil?
    end

    def new
      @skill = Skill.new
    end

    def create
      if (@skill = Skill.create(skill_params)) && @skill.valid?
        return redirect_to admin_skill_path(@skill)
      end

      render 'admin/skills/new'
    end

    def edit
      @skill = Skill.find_by(id: params[:id])
      not_found if @skill.nil?
    end

    def update
      @skill = Skill.find_by id: params[:id]
      not_found if @skill.nil?

      @skill.update(skill_params)

      if @skill.valid?
        return redirect_to admin_skill_path(@skill), notice: t('.success')
      end

      render 'admin/skills/edit'
    end

    def destroy
      @skill = Skill.find_by id: params[:id]
      not_found if @skill.nil?
      @skill.destroy

      if @skill.frozen?
        redirect_to admin_skills_path, notice: t('.success')
      else
        redirect_to admin_skills_path, alert: t('.error')
      end
    end

    private

    def skill_params
      params.require(:skill).permit(:title,
                                    :svg_logo,
                                    :image_logo,
                                    :level,
                                    case_study_ids: [])
    end
  end
end

app/controllers/skills_controller.rb
# Allow the user to see skills.
#
# @author Matthew Rayner
# @since 0.2
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end
end

app/views/admin/skills/edit.html.haml
-content_for :title, 'New Skill : Dashboard : Matt Rayner'

.jumbotron
  %h1= "Edit '#{@skill.title}'"
  %p.lead
    Create a skill and link it to case studies to show your ability.

= render 'admin/shared/validation', object: @skill

= simple_form_for(@skill, url: admin_skill_path(@skill), html: { class: 'form-horizontal' }) do |form|
  = render 'admin/skills/shared/form_fields', form: form

app/views/admin/skills/index.html.haml
-content_for :title, 'Skills : Dashboard : Matt Rayner'

.jumbotron
  %h1
    Skills
    %small= @skills.count
  %p.lead
    Create skills and link them to case studies to show your ability.
  %p
    = link_to 'Create Skill', new_admin_skill_path, class: 'btn btn-lg btn-success', role: 'button'

%table.table
  %thead
    %tr
      %th Title
      %th Controls
  %tbody
    - if @skills.count.zero?
      %tr
        %td{ colspan: 2 }
          Please
          = link_to 'add a skill', new_admin_skill_path
          to see it here.
    - else
      - @skills.each do |skill|
        = render 'admin/skills/shared/skill_row', skill: skill

app/views/admin/skills/new.html.haml
-content_for :title, 'New Skill : Dashboard : Matt Rayner'

.jumbotron
  %h1 New Skill
  %p.lead
    Create a skill and link it to case studies to show your ability.

= render 'admin/shared/validation', object: @skill

= simple_form_for(@skill, url: admin_skills_path, html: { class: 'form-horizontal' }) do |form|
  = render 'admin/skills/shared/form_fields', form: form

app/views/admin/skills/show.html.haml
-content_for :title, "View #{truncate(@skill.title, length: 20)} : Skills : Dashboard : Matt Rayner"

.jumbotron
  %h1
    Skill Preview
  %p
    = link_to 'All Skills', admin_skills_path, class: 'btn btn-lg btn-default'
    = link_to 'Edit Skill', edit_admin_skill_path(@skill), class: 'btn btn-lg btn-success pull-right'

%h2
  = @skill.title
.progress
  .progress-bar{ role: 'progressbar', aria: { valuenow: "#{@skill.level}", valuemin: '0', valuemax: '100' }, style: "width: #{@skill.level}%;" }
    %span.sr-only= "#{@skill.level}%"

- if @skill.case_studies
  .row-fluid
    - @skill.case_studies.each do |case_study|
      .col-md-4.skill-case-study
        %h3= link_to case_study.title, admin_case_study_path(case_study)
        - if case_study.intro.present?
          .case-study-intro
            = markdown(case_study.intro)