config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'

  resources :case_studies, only: [:index, :show ]
  resources :skills, only: [:index, :show ]

  namespace :admin do
    get '/' => 'dashboard#index', as: 'dashboard_index'

    resources :case_studies
    resources :case_study_gallery_images, only: [:edit, :update]

    resources :fit_bit_stats, only: [:index]

    resources :skills

    resources :curriculum_vitaes
  end
end

app/models/case_study_gallery_image.rb
# @author Matthew Rayner
# @since 0.1
class CaseStudyGalleryImage < ActiveRecord::Base
  validates :image,
            presence: {
              message: I18n.t('.case_study_gallery_image.image_validation')
            }
  validates_length_of :title, maximum: 255

  mount_uploader :image, GalleryImageUploader

  belongs_to :case_study
end

app/controllers/admin/case_study_gallery_images_controller.rb
module Admin
  # Allow a user to edit and update case study gallery images from within the
  # admin interface.
  #
  # @author Matthew Rayner
  # @since 0.1
  class CaseStudyGalleryImagesController < Admin::BaseController
    def edit
      @case_study_gallery_image = CaseStudyGalleryImage.find_by(id: params[:id])
      not_found if @case_study_gallery_image.nil?
    end

    def update
      @case_study_gallery_image = CaseStudyGalleryImage.find_by(id: params[:id])
      not_found if @case_study_gallery_image.nil?

      path = edit_admin_case_study_gallery_image_path(@case_study_gallery_image)

      if @case_study_gallery_image.update(case_study_gallery_image_params)
        redirect_to path, notice: t('.success')
      else
        redirect_to path, alert: t('.error')
      end
    end

    private

    def case_study_gallery_image_params
      params.require(:case_study_gallery_image).permit(:title,
                                                       :image,
                                                       :remove_image)
    end
  end
end

app/views/admin/case_study_gallery_images/shared/_form.html.haml
= simple_form_for(@case_study_gallery_image, url: admin_case_study_gallery_image_path(@case_study_gallery_image), html: { class: 'form-horizontal' }) do |form|
  .row
    .col-md-8
      .form-group
        .col-sm-12
          = form.label :title
        = form.text_field :title, class: 'form-control'

      - if @case_study_gallery_image.image?
        .well
          = image_tag @case_study_gallery_image.image, class: 'img-responsive'
          = link_to 'See full-size image', @case_study_gallery_image.image.url, target: '_blank'
      = form.input :image, input_html: { accept: '.jpg,.jpeg,.gif,.png' }

  .row
    .col-sm-6.text-left
      = link_to 'Back to Case Study', admin_case_study_path(@case_study_gallery_image.case_study), class: 'btn btn-lg btn-default'
    .col-sm-6.text-right
      = form.submit 'Save', class: 'btn btn-lg btn-success'

app/views/admin/case_study_gallery_images/shared/_form_fields.html.haml
= simple_form_for(@case_study_gallery_image, url: admin_case_study_gallery_image_path(@case_study_gallery_image), html: { class: 'form-horizontal' }) do |form|
  .row
    .col-md-8
      .form-group
        .col-sm-12
          = form.label :title
        = form.text_field :title, class: 'form-control'

      - if @case_study_gallery_image.image?
        .well
          = image_tag @case_study_gallery_image.image, class: 'img-responsive'
          = link_to 'See full-size image', @case_study_gallery_image.image.url, target: '_blank'
      .form-group
        .col-sm-12
          = form.label :image, 'Update image'
        .clearfix
        = form.file_field :image

  .row
    .col-sm-6.text-left
      = link_to 'Back to Case Study', admin_case_study_path(@case_study_gallery_image.case_study), class: 'btn btn-lg btn-default'
    .col-sm-6.text-right
      = form.submit 'Save', class: 'btn btn-lg btn-success'