config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'

  resources :case_studies, only: [:index, :show ]
  resources :skills, only: [:index, :show ]

  namespace :admin do
    get '/' => 'dashboard#index', as: 'dashboard_index'

    resources :case_studies
    resources :case_study_gallery_images, only: [:edit, :update]

    resources :fit_bit_stats, only: [:index]

    resources :skills

    resources :curriculum_vitaes
  end
end

app/controllers/home_controller.rb
# Allow the user to see a homepage.
#
# @author Matthew Rayner
# @since 0.1
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.haml
- content_for(:title, 'Matt Rayner : Full Stack Rubyist in London')
- content_for(:breadcrumbs, build_breadcrumbs)

.full-bleed-image.header.home
  .container
    .home-content
      %span.sr-only
        %h1 Matt Rayner
        %p.lead Full stack Rubyist in London

.container.container-small.text-center
  .header-divider

.container.container-small.text-center
  %h3.text-open-sans I design and develop beautiful things for print, online and the web
  %p.lead I make an amazing cup of tea too

.full-bleed-image.home-case-studies.bleed-glow
.container.container-small.text-center
  %h2 I Live and Breathe Digital Online
  %h3 Everything from SaaS cloud applications to e-commerce stores, CMS’s to iOS apps
  %p.lead I’ve made them, often for challenging clients in constraining time frames
  = link_to 'View Case Studies <span class="glyphicon glyphicon-chevron-right"></span>'.html_safe, case_studies_url, class: 'btn btn-lg btn-primary btn-pill btn-cta'

.full-bleed-image.home-skills.bleed-glow
.container.container-small.text-center
  %h2 I've Got a Wide Set of Skills
  %h3 Everything from server management to jQuery, Ruby to ActionScript
  %p.lead I'm a perfect fit for your large or small team
  = link_to 'View Skills <span class="glyphicon glyphicon-chevron-right"></span>'.html_safe, skills_url, class: 'btn btn-lg btn-primary btn-pill btn-cta'