config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'home#index'

  resources :case_studies, only: [:index, :show ]
  resources :skills, only: [:index, :show ]

  namespace :admin do
    get '/' => 'dashboard#index', as: 'dashboard_index'

    resources :case_studies
    resources :case_study_gallery_images, only: [:edit, :update]

    resources :fit_bit_stats, only: [:index]

    resources :skills

    resources :curriculum_vitaes
  end
end

app/models/case_study.rb
# @author Matthew Rayner
# @since 0.1
class CaseStudy < ActiveRecord::Base
  validates :title,
            presence: { message: I18n.t('.case_study.title_validation') }
  validates :body,
            presence: { message: I18n.t('.case_study.body_validation') }
  validates_length_of :title, maximum: 255

  mount_uploader :header_image, HeaderUploader

  has_many :gallery_images,
           foreign_key: 'case_study_id',
           class_name: 'CaseStudyGalleryImage'
  accepts_nested_attributes_for :gallery_images

  has_and_belongs_to_many :skills
end

app/controllers/admin/case_studies_controller.rb
module Admin
  # Allow a user to view, create and edit case studies from within the admin
  # interface.
  #
  # @author Matthew Rayner
  # @since 0.1
  class CaseStudiesController < Admin::BaseController
    def index
      @case_studies = CaseStudy.all
    end

    def new
      @case_study = CaseStudy.new
    end

    def edit
      @case_study = CaseStudy.find_by id: params[:id]

      not_found if @case_study.nil?
    end

    def show
      @case_study = CaseStudy.find_by id: params[:id]

      not_found if @case_study.nil?
    end

    def create
      @case_study = CaseStudy.create(case_study_params)

      create_gallery_images if @case_study && valid_case_study?

      if valid_case_study?
        redirect_to admin_case_study_path(@case_study)
      else
        render 'admin/case_studies/new'
      end
    end

    def update
      @case_study = CaseStudy.find_by id: params[:id]
      not_found if @case_study.nil?

      @case_study.update(case_study_params)

      if valid_case_study?
        update_gallery_images

        create_gallery_images

        redirect_to admin_case_study_path(@case_study), notice: t('.success')
      else
        render 'admin/case_studies/edit'
      end
    end

    def destroy
      @case_study = CaseStudy.find_by id: params[:id]
      not_found if @case_study.nil?

      @case_study.destroy

      if @case_study.frozen?
        redirect_to admin_case_studies_path, notice: t('.success')
      else
        redirect_to admin_case_studies_path, alert: t('.error')
      end
    end

    private

    def case_study_params
      params.require(:case_study).permit(:title, :intro, :body, :header_image,
                                         :remove_header_image,
                                         skill_ids: [],
                                         gallery_images_attributes:
                                           [:id,
                                            :case_study_id, :image,
                                            :remove_image])
    end

    def create_gallery_images
      fetch_gallery_images.each do |image|
        @case_study.gallery_images.create!(image: image,
                                           case_study_id: @case_study.id)
      end
    end

    def update_gallery_images
      fetch_gallery_image_attributes.each do |image|
        image = image[1]

        if image[:remove_image] == '1'
          @gallery_image = CaseStudyGalleryImage.find_by(id: image[:id])
          @gallery_image.destroy unless @gallery_image.nil?
        end
      end
    end

    def valid_case_study?
      @case_study.valid?
    end

    def fetch_gallery_images
      params.fetch(:case_study_gallery_images, {}).fetch(:images, [])
    end

    def fetch_gallery_image_attributes
      params.fetch(:case_study, {}).fetch(:gallery_images_attributes, [])
    end
  end
end

app/controllers/case_studies_controller.rb
# Allow the user to see case studies.
#
# @author Matthew Rayner
# @since 0.2
class CaseStudiesController < ApplicationController
  def index
    @case_studies = CaseStudy.all
  end

  def show
    @case_study = CaseStudy.find_by(id: params[:id])
    not_found if @case_study.nil?
  end
end

app/views/case_studies/index.html.haml
- content_for(:title, 'Case Studies : Matt Rayner : Full Stack Rubyist in London')
- content_for(:breadcrumbs, build_breadcrumbs({title: 'Case Studies', url: case_studies_url}))

.full-bleed-image.header.case-studies
  .container
    .case-studies-content
      %span.sr-only
        %h1 Case Studies

.container.container-small.text-center.divider-container
  .header-divider

.container.container-small.text-center
  %h3.text-open-sans I design and develop beautiful things for print, online and the web
  %p.lead I make an amazing cup of tea too

- @case_studies.each do |case_study|
  = render 'case_studies/shared/case_study_listing', case_study: case_study

app/views/case_studies/show.html.haml
- content_for(:title, "#{@case_study.title} : Case Studies : Matt Rayner : Full Stack Rubyist in London")
- content_for(:breadcrumbs, build_breadcrumbs([{title: 'Case Studies', url: case_studies_url}, {title: @case_study.title, url: case_study_url(@case_study)}]))

.full-bleed-image.header.case-studies.data-image.bleed-glow{ data: { large_image: @case_study.header_image.retina_banner.url, image: @case_study.header_image.banner.url} }
  .container
    .case-study-content
      %h1= @case_study.title

.container.container-small.text-center
  =markdown(@case_study.intro)

.container.container-small.text-center
  =markdown(@case_study.body)

- if @case_study.gallery_images.present?
  .container.container-small.text-center
    %h2 Gallery
    - @case_study.gallery_images.each do |image|
      = image_tag image.image.blurred_background.url
      = image_tag image.image.thumb.url, width: 150

- if @case_study.skills.present?
  .container.container-small.text-center
    %h2 Skills
    - @case_study.skills.each do |skill|
      = skill.title